# Generated by Django 3.0.4 on 2020-04-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_username', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOriginalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_name', models.CharField(max_length=200, null=True)),
                ('original_image', models.ImageField(null=True, upload_to='')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('the_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagefilters.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserEditedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_image_name', models.CharField(max_length=200, null=True)),
                ('edited_image', models.ImageField(null=True, upload_to='')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('original_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagefilters.UserOriginalImage')),
            ],
        ),
    ]
